# The contents of this file are parsed and made available as
# via `site.*`. So for example, {{ site.title }} can be used
# in a template to get the contents of the `title` key.
title: At The Keyboard 
subtitle: Chris Hartjes sharing grumpy wisdom since 2005 

# Insert your disqus shortname
#disqus:
#    shortname:
